
   export  const  totalproducts =[



        {
            "id": 1,
            "image": "https://images.pexels.com/photos/17515570/pexels-photo-17515570/free-photo-of-furniture-set-in-studio.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
            "name": "Comfy Armchair",
            "price": 199.99,
            "categories": "Home",
            "quantity" : 1,
            "details": "Relatively Comfy Armchair is part of “ALUCUTS” (2021 – 2023) furniture series, showcasing simple yet sturdy bolted assemblies of 12mm squared cuts of aluminium plates. The cuts are organized empirically until the piece reveals itself. Craft is kept to its bare minimum: the shiny edges are scarred by the blade, and contrast with the brushed finish; countersunk Allen bolts details underline the connections."
          },
          {
            "id": 2,
            "image": "https://images.pexels.com/photos/534151/pexels-photo-534151.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
            "name": "Modern Dining Table",
            "price": 349.99,
            "categories": "Office",
            "quantity" : 1,
            "details": "Relatively Comfy Armchair is part of “ALUCUTS” (2021 – 2023) furniture series, showcasing simple yet sturdy bolted assemblies of 12mm squared cuts of aluminium plates. The cuts are organized empirically until the piece reveals itself. Craft is kept to its bare minimum: the shiny edges are scarred by the blade, and contrast with the brushed finish; countersunk Allen bolts details underline the connections."
          },
          {
            "id": 3,
            "image": "https://images.pexels.com/photos/6980714/pexels-photo-6980714.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
            "name": "L-Shaped Sofa",
            "price": 799.99,
            "categories": "Home",
            "quantity" : 1,
            "details": "Relatively Comfy Armchair is part of “ALUCUTS” (2021 – 2023) furniture series, showcasing simple yet sturdy bolted assemblies of 12mm squared cuts of aluminium plates. The cuts are organized empirically until the piece reveals itself. Craft is kept to its bare minimum: the shiny edges are scarred by the blade, and contrast with the brushed finish; countersunk Allen bolts details underline the connections."
          },
          {
            "id": 4,
            "image": "https://images.pexels.com/photos/6207458/pexels-photo-6207458.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
            "name": "Queen Size Bed",
            "price": 599.99,
            "categories": "Home",
            "quantity" : 1,
            "details": "Relatively Comfy Armchair is part of “ALUCUTS” (2021 – 2023) furniture series, showcasing simple yet sturdy bolted assemblies of 12mm squared cuts of aluminium plates. The cuts are organized empirically until the piece reveals itself. Craft is kept to its bare minimum: the shiny edges are scarred by the blade, and contrast with the brushed finish; countersunk Allen bolts details underline the connections."
          },
          {
            "id": 5,
            "image": "https://images.pexels.com/photos/1125135/pexels-photo-1125135.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
            "name": "Modern Bookshelf",
            "price": 159.99,
            "categories": "Office",
            "quantity" : 1,
            "details": "Relatively Comfy Armchair is part of “ALUCUTS” (2021 – 2023) furniture series, showcasing simple yet sturdy bolted assemblies of 12mm squared cuts of aluminium plates. The cuts are organized empirically until the piece reveals itself. Craft is kept to its bare minimum: the shiny edges are scarred by the blade, and contrast with the brushed finish; countersunk Allen bolts details underline the connections."
          },
          {
            "id": 6,
            "image": "https://images.pexels.com/photos/4099354/pexels-photo-4099354.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
            "name": "Coffee Table",
            "price": 129.99,
            "categories": "Home",
            "quantity" : 1,
            "details": "Relatively Comfy Armchair is part of “ALUCUTS” (2021 – 2023) furniture series, showcasing simple yet sturdy bolted assemblies of 12mm squared cuts of aluminium plates. The cuts are organized empirically until the piece reveals itself. Craft is kept to its bare minimum: the shiny edges are scarred by the blade, and contrast with the brushed finish; countersunk Allen bolts details underline the connections."
          },
          {
            "id": 7,
            "image": "https://images.pexels.com/photos/4993050/pexels-photo-4993050.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
            "name": "Nightstand",
            "price": 79.99,
            "categories": "featured",
            "quantity" : 1,
            "details": "Relatively Comfy Armchair is part of “ALUCUTS” (2021 – 2023) furniture series, showcasing simple yet sturdy bolted assemblies of 12mm squared cuts of aluminium plates. The cuts are organized empirically until the piece reveals itself. Craft is kept to its bare minimum: the shiny edges are scarred by the blade, and contrast with the brushed finish; countersunk Allen bolts details underline the connections."
          },
          {
            "id": 8,
            "image": "https://images.pexels.com/photos/3653849/pexels-photo-3653849.jpeg?auto=compress&cs=tinysrgb&w=400",
            "name": "Office table",
            "price": 249.99,
            "categories": "featured",
            "quantity" : 1,
            "details": "Relatively Comfy Armchair is part of “ALUCUTS” (2021 – 2023) furniture series, showcasing simple yet sturdy bolted assemblies of 12mm squared cuts of aluminium plates. The cuts are organized empirically until the piece reveals itself. Craft is kept to its bare minimum: the shiny edges are scarred by the blade, and contrast with the brushed finish; countersunk Allen bolts details underline the connections."
          },
          {
            "id": 9,
            "image": "https://images.pexels.com/photos/5824901/pexels-photo-5824901.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
            "name": "Leather Couch",
            "price": 899.99,
            "categories": "featured",
            "quantity" : 1,
            "details": "Relatively Comfy Armchair is part of “ALUCUTS” (2021 – 2023) furniture series, showcasing simple yet sturdy bolted assemblies of 12mm squared cuts of aluminium plates. The cuts are organized empirically until the piece reveals itself. Craft is kept to its bare minimum: the shiny edges are scarred by the blade, and contrast with the brushed finish; countersunk Allen bolts details underline the connections."
          },
          {
            "id": 10,
            "image": "https://images.pexels.com/photos/6782465/pexels-photo-6782465.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
            "name": "Wardrobe",
            "price": 499.99,
            "categories": "Closet",
            "quantity" : 1,
            "details": "Relatively Comfy Armchair is part of “ALUCUTS” (2021 – 2023) furniture series, showcasing simple yet sturdy bolted assemblies of 12mm squared cuts of aluminium plates. The cuts are organized empirically until the piece reveals itself. Craft is kept to its bare minimum: the shiny edges are scarred by the blade, and contrast with the brushed finish; countersunk Allen bolts details underline the connections."
          },
          // {
          //   "id": 11,
          //   "image": "https://example.com/dresser.jpg",
          //   "name": "Dresser",
          //   "price": 349.99,
          //   "categories": "Bedroom Furniture",
          //   "quantity" : 1,
          //   "details": "Relatively Comfy Armchair is part of “ALUCUTS” (2021 – 2023) furniture series, showcasing simple yet sturdy bolted assemblies of 12mm squared cuts of aluminium plates. The cuts are organized empirically until the piece reveals itself. Craft is kept to its bare minimum: the shiny edges are scarred by the blade, and contrast with the brushed finish; countersunk Allen bolts details underline the connections."
          // },
          // {
          //   "id": 12,
          //   "image": "https://example.com/shoe-rack.jpg",
          //   "name": "Shoe Rack",
          //   "price": 59.99,
          //   "categories": "Storage",
          //   "quantity" : 1,
          // },
          // {
          //   "id": 13,
          //   "image": "https://example.com/tv-stand.jpg",
          //   "name": "TV Stand",
          //   "price": 199.99,
          //   "categories": "Entertainment",
          //   "quantity" : 1,
          // },
          // {
          //   "id": 14,
          //   "image": "https://example.com/cabinet.jpg",
          //   "name": "Storage Cabinet",
          //   "price": 179.99,
          //   "categories": "Storage",
          //   "quantity" : 1,
          // },
          // {
          //   "id": 15,
          //   "image": "https://example.com/study-chair.jpg",
          //   "name": "Study Chair",
          //   "price": 79.99,
          //   "categories": "Chairs",
          //   "quantity" : 1,
          // },
          // {
          //   "id": 16,
          //   "image": "https://example.com/sofa-bed.jpg",
          //   "name": "Sofa Bed",
          //   "price": 549.99,
          //   "categories": "Sofas",
          //   "quantity" : 1,
          // },
          // {
          //   "id": 17,
          //   "image": "https://example.com/bar-stool.jpg",
          //   "name": "Bar Stool",
          //   "price": 89.99,
          //   "categories": "Chairs",
          //   "quantity" : 1,
          // },
          // {
          //   "id": 18,
          //   "image": "https://example.com/side-table.jpg",
          //   "name": "Side Table",
          //   "price": 49.99,
          //   "categories": "Tables",
          //   "quantity" : 1,
          // },
          // {
          //   "id": 19,
          //   "image": "https://example.com/chest-of-drawers.jpg",
          //   "name": "Chest of Drawers",
          //   "price": 279.99,
          //   "categories": "Bedroom Furniture",
          //   "quantity" : 1,
          // },
          // {
          //   "id": 20,
          //   "image": "https://example.com/bean-bag.jpg",
          //   "name": "Bean Bag Chair",
          //   "price": 69.99,
          //   "categories": "Chairs",
          //   "quantity" : 1,
          // },
          // {
          //   "id": 21,
          //   "image": "https://example.com/rocking-chair.jpg",
          //   "name": "Rocking Chair",
          //   "price": 149.99,
          //   "categories": "Chairs",
          //   "quantity" : 1,
          // },
          // {
          //   "id": 22,
          //   "image": "https://example.com/folding-table.jpg",
          //   "name": "Folding Table",
          //   "price": 79.99,
          //   "categories": "Tables",
          //   "quantity" : 1,
          // },
          // {
          //   "id": 23,
          //   "image": "https://example.com/bookcase.jpg",
          //   "name": "Bookcase",
          //   "price": 179.99,
          //   "categories": "Shelves",
          //   "quantity" : 1,
          // },
          // {
          //   "id": 24,
          //   "image": "https://example.com/office-chair.jpg",
          //   "name": "Office Chair",
          //   "price": 129.99,
          //   "categories": "Chairs",
          //   "quantity" : 1,
          // },
          // {
          //   "id": 25,
          //   "image": "https://example.com/dining-chair.jpg",
          //   "name": "Dining Chair",
          //   "price": 69.99,
          //   "categories": "Chairs",
          //   "quantity" : 1,
          // },
          // {
          //   "id": 26,
          //   "image": "https://example.com/bunk-bed.jpg",
          //   "name": "Bunk Bed",
          //   "price": 599.99,
          //   "categories": "Beds",
          //   "quantity" : 1,
          // },
          // {
          //   "id": 27,
          //   "image": "https://example.com/end-table.jpg",
          //   "name": "End Table",
          //   "price": 59.99,
          //   "categories": "Tables",
          //   "quantity" : 1,
          // },
          // {
          //   "id": 28,
          //   "image": "https://example.com/corner-sofa.jpg",
          //   "name": "Corner Sofa",
          //   "price": 849.99,
          //   "categories": "Sofas",
          //   "quantity" : 1,
          // },
          // {
          //   "id": 29,
          //   "image": "https://example.com/desk-chair.jpg",
          //   "name": "Desk Chair",
          //   "price": 129.99,
          //   "categories": "Chairs",
          //   "quantity" : 1,
          // },
          // {
          //   "id": 30,
          //   "image": "https://example.com/shelving-unit.jpg",
          //   "name": "Shelving Unit",
          //   "price": 299.99,
          //   "categories": "Shelves",
          //   "quantity" : 1,
          // },
          // {
          //   "id": 31,
          //   "image": "https://example.com/counter-stool.jpg",
          //   "name": "Counter Stool",
          //   "price": 79.99,
          //   "categories": "Chairs",
          //   "quantity" : 1,
          // },
          // {
          //   "id": 32,
          //   "image": "https://example.com/bedside-table.jpg",
          //   "name": "Bedside Table",
          //   "price": 49.99,
          //   "categories": "Bedroom Furniture",
          //   "quantity" : 1,
          // },
          // {
          //   "id": 33,
          //   "image": "https://example.com/corner-desk.jpg",
          //   "name": "Corner Desk",
          //   "price": 249.99,
          //   "categories": "Desks",
          //   "quantity" : 1,
          // },
          // {
          //   "id": 34,
          //   "image": "https://example.com/lounge-chair.jpg",
          //   "name": "Lounge Chair",
          //   "price": 199.99,
          //   "categories": "Chairs",
          //   "quantity" : 1,
          // },
          // {
          //   "id": 35,
          //   "image": "https://example.com/storage-bench.jpg",
          //   "name": "Storage Bench",
          //   "price": 119.99,
          //   "categories": "Benches",
          //   "quantity" : 1,
          // },
          // {
          //   "id": 36,
          //   "image": "https://example.com/sectional-sofa.jpg",
          //   "name": "Sectional Sofa",
          //   "price": 1299.99,
          //   "categories": "Sofas",
          //   "quantity" : 1,
          // },
          // {
          //   "id": 37,
          //   "image": "https://example.com/shoe-cabinet.jpg",
          //   "name": "Shoe Cabinet",
          //   "price": 149.99,
          //   "categories": "Storage",
          //   "quantity" : 1,
          // },
          // {
          //   "id": 38,
          //   "image": "https://example.com/armchair.jpg",
          //   "name": "Armchair",
          //   "price": 179.99,
          //   "categories": "Chairs",
          //   "quantity" : 1,
          // },
          // {
          //   "id": 39,
          //   "image": "https://example.com/entryway-table.jpg",
          //   "name": "Entryway Table",
          //   "price": 99.99,
          //   "categories": "Tables",
          //   "quantity" : 1,
          // },
          // {
          //   "id": 40,
          //   "image": "https://example.com/mirror.jpg",
          //   "name": "Wall Mirror",
          //   "price": 69.99,
          //   "categories": "Decor",
          //   "quantity" : 1,
          // },
          // {
          //   "id": 41,
          //   "image": "https://example.com/clothes-rack.jpg",
          //   "name": "Clothes Rack",
          //   "price": 79.99,
          //   "categories": "Storage",
          //   "quantity" : 1,
          // },
          // {
          //   "id": 42,
          //   "image": "https://example.com/accent-chair.jpg",
          //   "name": "Accent Chair",
          //   "price": 199.99,
          //   "categories": "Chairs",
          //   "quantity" : 1,
          // },
          // {
          //   "id": 43,
          //   "image": "https://example.com/dining-table.jpg",
          //   "name": "Dining Table",
          //   "price": 599.99,
          //   "categories": "Tables",
          //   "quantity" : 1,
          // },
          // {
          //   "id": 44,
          //   "image": "https://example.com/hallway-bench.jpg",
          //   "name": "Hallway Bench",
          //   "price": 149.99,
          //   "categories": "Benches",
          //   "quantity" : 1,
          // },
          // {
          //   "id": 45,
          //   "image": "https://example.com/console-table.jpg",
          //   "name": "Console Table",
          //   "price": 129.99,
          //   "categories": "Tables",
          //   "quantity" : 1,
          // },
          // {
          //   "id": 46,
          //   "image": "https://example.com/loveseat.jpg",
          //   "name": "Loveseat",
          //   "price": 599.99,
          //   "categories": "Sofas",
          //   "quantity" : 1,
          // },
          // {
          //   "id": 47,
          //   "image": "https://example.com/folding-chair.jpg",
          //   "name": "Folding Chair",
          //   "price": 49.99,
          //   "categories": "Chairs",
          //   "quantity" : 1,
          // },
          // {
          //   "id": 48,
          //   "image": "https://example.com/file-cabinet.jpg",
          //   "name": "File Cabinet",
          //   "price": 89.99,
          //   "categories": "Storage",
          //   "quantity" : 1,
          // },
          // {
          //   "id": 49,
          //   "image": "https://example.com/bed-frame.jpg",
          //   "name": "Bed Frame",
          //   "price": 249.99,
          //   "categories": "Beds",
          //   "quantity" : 1,
          // },
          // {
          //   "id": 50,
          //   "image": "https://example.com/mid-century-sofa.jpg",
          //   "name": "Mid-Century Sofa",
          //   "price": 799.99,
          //   "categories": "Sofas",
          //   "quantity" : 1,
          // },
          //   {
          //     "id": 51,
          //     "image": "https://example.com/wooden-chair.jpg",
          //     "name": "Wooden Dining Chair",
          //     "price": 79.99,
          //     "categories": "Chairs",
          //     "quantity" : 1,
          //   },
          //   {
          //     "id": 52,
          //     "image": "https://example.com/counter-height-table.jpg",
          //     "name": "Counter Height Dining Table",
          //     "price": 299.99,
          //     "categories": "Tables",
          //     "quantity" : 1,
          //   },
          //   {
          //     "id": 53,
          //     "image": "https://example.com/leather-sectional.jpg",
          //     "name": "Leather Sectional Sofa",
          //     "price": 1299.99,
          //     "categories": "Sofas",
          //     "quantity" : 1,
          //   },
          //   {
          //     "id": 54,
          //     "image": "https://example.com/dressing-table.jpg",
          //     "name": "Dressing Table",
          //     "price": 199.99,
          //     "categories": "Bedroom Furniture",
          //     "quantity" : 1,
          //   },
          //   {
          //     "id": 55,
          //     "image": "https://example.com/corner-bookshelf.jpg",
          //     "name": "Corner Bookshelf",
          //     "price": 89.99,
          //     "categories": "Shelves",
          //     "quantity" : 1,
          //   },
          //   {
          //     "id": 56,
          //     "image": "https://example.com/chaise-lounge.jpg",
          //     "name": "Chaise Lounge",
          //     "price": 349.99,
          //     "categories": "Chairs",
          //     "quantity" : 1,
          //   },
          //   {
          //     "id": 57,
          //     "image": "https://example.com/metal-bed-frame.jpg",
          //     "name": "Metal Bed Frame",
          //     "price": 199.99,
          //     "categories": "Beds",
          //     "quantity" : 1,
          //   },
          //   {
          //     "id": 58,
          //     "image": "https://example.com/kids-desk.jpg",
          //     "name": "Kids Desk",
          //     "price": 149.99,
          //     "categories": "Desks",
          //     "quantity" : 1,
          //   },
          //   {
          //     "id": 59,
          //     "image": "https://example.com/futon-sofa-bed.jpg",
          //     "name": "Futon Sofa Bed",
          //     "price": 299.99,
          //     "categories": "Sofas",
          //     "quantity" : 1,
          //   },
          //   {
          //     "id": 60,
          //     "image": "https://example.com/folding-bookcase.jpg",
          //     "name": "Folding Bookcase",
          //     "price": 79.99,
          //     "categories": "Shelves",
          //     "quantity" : 1,
          //   },
    ];
